---
- name: Copy jar file from GitHub to server
  hosts: http://localhost/
  gather_facts: false

  vars:
    github_repo_url: "https://github.com/zeina-se/deploy_ansible.git"
    jar_file_path: "test.jpg"

  tasks:
    - name: Clone GitHub repository
      git:
        repo: "{{ github_repo_url }}"
        dest: "/images/"
        version: master

    - name: Copy jar file to server
      copy:
        src: "/tmp/your_github_repo/{{ jar_file_path }}"
        dest: "/images/{{ jar_file_path }}"