---
- hosts: webservers
  tasks:
    - name: Install Apache web server
      apt:
        name: apache2
        state: present
    - name: Copy index.html file
      copy:
        src: index.html
        dest: C:\Users\Admin\Desktop\DevOps\deploy_ansible\index.html
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
